import { LegalLayout } from '../components/legal/LegalLayout';
import { LegalSection } from '../components/legal/LegalSection';
import type { TocItem } from '../components/legal/TableOfContents';

const LAST_UPDATED = '2026-07-10';

const PRIVACY_TOC: TocItem[] = [
  { id: 'introduction', title: 'Introduction' },
  { id: 'information-we-collect', title: 'Information We Collect' },
  { id: 'how-information-is-used', title: 'How Information Is Used' },
  { id: 'firebase-authentication', title: 'Firebase Authentication' },
  { id: 'cloud-firestore-storage', title: 'Cloud Firestore Storage' },
  { id: 'local-storage-usage', title: 'Local Storage Usage' },
  { id: 'cookies', title: 'Cookies' },
  { id: 'analytics', title: 'Analytics' },
  { id: 'notifications', title: 'Notifications' },
  { id: 'data-security', title: 'Data Security' },
  { id: 'data-retention', title: 'Data Retention' },
  { id: 'user-rights', title: 'User Rights' },
  { id: 'delete-your-data', title: 'Delete Your Data' },
  { id: 'childrens-privacy', title: "Children's Privacy" },
  { id: 'third-party-services', title: 'Third Party Services' },
  { id: 'international-users', title: 'International Users' },
  { id: 'changes-to-this-policy', title: 'Changes To This Policy' },
  { id: 'contact-information', title: 'Contact Information' },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalLayout
      title="Privacy Policy"
      eyebrow="Privacy"
      description="How NorthHabit handles account, workspace, and device data with a local-first, user-owned mindset."
      lastUpdated={LAST_UPDATED}
      toc={PRIVACY_TOC}
    >
      <LegalSection id="introduction" title="Introduction">
        <p>
          NorthHabit is a productivity workspace for habits, todos, calendar planning, and focus
          sessions. This policy explains what information NorthHabit may collect, how it is used,
          and the choices you have. User data belongs to the user. NorthHabit never sells user data.
        </p>
        <p>
          NorthHabit is developed by Soumil Malviya and is available at
          {' '}
          <a href="https://northhabit.pages.dev">northhabit.pages.dev</a>.
        </p>
      </LegalSection>

      <LegalSection id="information-we-collect" title="Information We Collect">
        <p>
          NorthHabit collects only the information needed to provide the product, secure your
          account, and preserve your workspace.
        </p>
        <ul>
          <li>Google account information, if you choose Google sign-in.</li>
          <li>Email address.</li>
          <li>Name.</li>
          <li>Profile picture, if Google provides one.</li>
          <li>Habits, habit logs, targets, categories, and streak-related history.</li>
          <li>Todos, descriptions, completion state, and scheduled dates.</li>
          <li>Calendar events or calendar-like planning data created inside NorthHabit.</li>
          <li>Pomodoro settings, focus sessions, focus statistics, and focus grove data.</li>
          <li>App preferences, notification preferences, soundscape settings, and theme settings.</li>
          <li>Usage statistics generated by your activity in the app.</li>
        </ul>
      </LegalSection>

      <LegalSection id="how-information-is-used" title="How Information Is Used">
        <p>
          Information is used to authenticate you, restore your workspace, sync product data when
          cloud storage is enabled, personalize the interface, calculate statistics, and support
          essential product behavior such as reminders and settings.
        </p>
        <p>
          NorthHabit does not use your private productivity data for advertising, and it does not
          sell, rent, or broker user data.
        </p>
      </LegalSection>

      <LegalSection id="firebase-authentication" title="Firebase Authentication">
        <p>
          Authentication is handled securely by Firebase Authentication. Passwords are never stored
          by NorthHabit. When you sign in with Google, your Google credentials are never visible to
          the application. NorthHabit receives only the account information Google and Firebase make
          available for sign-in, such as your user identifier, email, name, and profile image.
        </p>
      </LegalSection>

      <LegalSection id="cloud-firestore-storage" title="Cloud Firestore Storage">
        <p>
          NorthHabit may use Cloud Firestore to store workspace data for signed-in users. This may
          include habits, todos, calendar-related entries, focus history, settings, and statistics.
          Firestore helps keep your workspace available across devices once cloud sync is enabled.
        </p>
      </LegalSection>

      <LegalSection id="local-storage-usage" title="Local Storage Usage">
        <p>
          NorthHabit uses browser local storage to keep the app fast, private, and resilient. Local
          storage may hold habits, todos, focus settings, theme preferences, onboarding status,
          notification preferences, and other app settings directly on your device.
        </p>
      </LegalSection>

      <LegalSection id="cookies" title="Cookies">
        <p>
          NorthHabit does not use advertising cookies. The app may use essential browser storage,
          including local storage, IndexedDB, or Firebase-managed storage, to keep sessions active
          and preserve product functionality.
        </p>
      </LegalSection>

      <LegalSection id="analytics" title="Analytics">
        <p>
          NorthHabit may use Firebase Analytics to understand product health and high-level usage.
          Analytics, if enabled, is used to improve reliability and product experience, not to sell
          user data or build advertising profiles.
        </p>
      </LegalSection>

      <LegalSection id="notifications" title="Notifications">
        <p>
          If you enable reminders, NorthHabit may use browser notification APIs to send habit,
          streak, or Pomodoro notifications. Notification settings remain under your control and can
          be changed in the app or through your browser settings.
        </p>
      </LegalSection>

      <LegalSection id="data-security" title="Data Security">
        <p>
          NorthHabit uses Firebase services and browser security controls to protect authentication
          and stored data. No web application can guarantee absolute security, but NorthHabit is
          designed to limit collection, keep credentials out of the application, and rely on
          established infrastructure for account security.
        </p>
      </LegalSection>

      <LegalSection id="data-retention" title="Data Retention">
        <p>
          NorthHabit retains account and workspace data for as long as your account remains active
          or as needed to provide the service. Data stored locally may remain on your device until
          you clear browser storage or use an app-provided deletion or import flow.
        </p>
      </LegalSection>

      <LegalSection id="user-rights" title="User Rights">
        <p>
          You may request access, correction, export, or deletion of your account data. You may also
          control local browser storage, revoke notification permissions, or disconnect Google
          access through your Google account settings.
        </p>
      </LegalSection>

      <LegalSection id="delete-your-data" title="Delete Your Data">
        <p>
          Users may request account deletion by contacting
          {' '}
          <a href="mailto:soumil.malviya@icloud.com">soumil.malviya@icloud.com</a>. Deletion
          requests should be sent from the email associated with the NorthHabit account when
          possible. Local data can also be removed by clearing site data in your browser.
        </p>
      </LegalSection>

      <LegalSection id="childrens-privacy" title="Children's Privacy">
        <p>
          NorthHabit is not directed to children under 13. If you believe a child has provided
          personal information through NorthHabit, contact us so the information can be reviewed and
          removed where appropriate.
        </p>
      </LegalSection>

      <LegalSection id="third-party-services" title="Third Party Services">
        <p>NorthHabit relies on a small set of infrastructure providers:</p>
        <ul>
          <li>Firebase, including Firebase Authentication, Cloud Firestore, and Firebase Analytics.</li>
          <li>Google Authentication, when you choose to sign in with Google.</li>
          <li>Cloudflare Pages, used to host and deliver the website.</li>
        </ul>
        <p>
          These services process information according to their own policies and security practices.
        </p>
      </LegalSection>

      <LegalSection id="international-users" title="International Users">
        <p>
          NorthHabit may be accessed from different countries. By using the service, you understand
          that information may be processed in locations where Firebase, Google, Cloudflare, or
          related infrastructure providers operate.
        </p>
      </LegalSection>

      <LegalSection id="changes-to-this-policy" title="Changes To This Policy">
        <p>
          This policy may change as NorthHabit evolves. Material updates will be reflected by a new
          last updated date and, where appropriate, additional notice in the product.
        </p>
      </LegalSection>

      <LegalSection id="contact-information" title="Contact Information">
        <p>
          For privacy questions, account deletion, or data requests, contact Soumil Malviya at
          {' '}
          <a href="mailto:soumil.malviya@icloud.com">soumil.malviya@icloud.com</a>.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
